#ifndef __mb_bulk_h__
#define __mb_bulk_h__

#include "ehw.h"

#define PKT_FLAGS_SEG_NUM_RST_FLAG  0x80
#define PKT_FLAGS_END_OF_SEQ_FLAG   0x40
#define PKT_FLAGS_TYPE_DESIGNATOR   0x00

typedef struct
{
	//uint8_t	sos;                // Internally consumed/generated by CS46L01
	char reserved;           // Always 0
	char payloadLen;         // 0..152
	char funcID;
	char pktFlags;
	char segNum;
} bulk_pkt_hdr_t;

typedef struct      // Format of packet in Downlink Bulk buffer
{
	bulk_pkt_hdr_t	hdr;
	char payload[152];   // 0..MAX_BULK_PACKET_PAYLOAD bytes
	char crc[2];
	char errFlags;
} bulk_pkt_t;

void mb_bulk_payload_tx(ehw *device, uint8 module, uint8 funcID, uint8 *payload, uint8 length);

#endif  // __mb_bulk_h__

